#!/bin/bash

#SBATCH -J abaqus
#SBATCH --ntasks-per-core=1
#SBATCH -o abaqus.%j.out
#SBATCH -n <<ncpu>>
#SBATCH -N 1

source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64

hostname
echo $SLURM_NTASKS

unset SLURM_GTIDS
/opt/abaqus/Commands/abq2019hf13 job=<<jobName>> cpus=$SLURM_NTASKS double inter 
