#!/bin/bash

#SBATCH -J abaqus
#SBATCH -B 2:24:1
#SBATCH -o abaqus.%j.out
#SBATCH -n <<ncpu>>

source /opt/ohpc/pub/apps/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64

hostname
echo $SLURM_NTASKS

unset SLURM_GTIDS
/opt/ohpc/pub/apps/abaqus/Commands/abq2019 job=<<jobName>> cpus=$SLURM_NTASKS double inter 
